In [1]:
import numpy as np
e=np.random.random((3,4))
print("Array with all zeros:\n",e)

Array with all zeros:
 [[0.92845991 0.64803309 0.00313859 0.21957811]
 [0.0920874  0.74101494 0.35098483 0.98873576]
 [0.10078622 0.01175722 0.12995434 0.56890112]]


In [3]:
import numpy as np
d=np.zeros((3,4))
print("Array with all zeros:\n",d)

Array with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
import numpy as np
f=np.arange(5,30,2)
print("Sequence array:",f)

Sequence array: [ 5  7  9 11 13 15 17 19 21 23 25 27 29]


In [5]:
import numpy as np
ar=np.array([[[1,2,3,4],[5,6,7,8,],[9,10,11,12]],[[0,2,3,4],[6,3,5,1],[9,0,3,6]]])
print("Three dimension array:\n",ar)
print("The dimension of the aray:",ar.ndim)
print("Shape of the array:",ar.shape)
print("Type of the array:",ar.dtype)

Three dimension array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 0  2  3  4]
  [ 6  3  5  1]
  [ 9  0  3  6]]]
The dimension of the aray: 3
Shape of the array: (2, 3, 4)
Type of the array: int64


In [7]:
import numpy as np
org=np.array([[1,2,3],[4,5,6]])
fl=org.flatten()
print("Original array:\n",org)
print("Flattened array:",fl)


Original array:
 [[1 2 3]
 [4 5 6]]
Flattened array: [1 2 3 4 5 6]
