In [4]:
#slicing without step
import numpy as np
#create a numpy array
arr=np.array([1,2,3,4,5,6,7,8,9])
#slice the index from 2 to 5
slice1=arr[2:5] #a to b-1
print("org:",arr,"\nsliced:",slice1)

org: [1 2 3 4 5 6 7 8 9] 
sliced: [3 4 5]


In [5]:
#slicing with step
slice2=arr[::2]
print(slice2)
slice3=arr[::3]
print(slice3)
slice4=arr[::4]
print(slice4)

[1 3 5 7 9]
[1 4 7]
[1 5 9]


In [6]:
#reversiing
revarr=arr[::-1]
print("reverse:",revarr)

reverse: [9 8 7 6 5 4 3 2 1]


In [11]:
#slicing multidimensional array
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarray1=arr[0:2,1:3]
print("sub array1:\n",subarray1)
subarray2=arr[0:3,0:2]
print("sub array2:\n",subarray2)
print("subarray3:\n",arr[:2,:1])

sub array1:
 [[2 3]
 [5 6]]
sub array2:
 [[1 2]
 [4 5]
 [7 8]]
subarray3:
 [[1]
 [4]]


In [19]:
#extract first column 
col1=arr[:,0]
print("column1:\n",col1)
#extract first row
print("row1:\n",arr[0,:])
#to return every other row
print("every other row:\n",arr[0:3:2])

column1:
 [1 4 7]
row1:
 [1 2 3]
every other row:
 [[1 2 3]
 [7 8 9]]


In [20]:
#array indexing for 1D arrray
import numpy as np
import array
arr=array.array('i',[10,20,30,40,50])
print(arr[0])
print(arr[3])

10
40


In [22]:
#array indexing for 2D array
import numpy as np
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2[0,0])
print(arr2[2,1])

1
8


In [35]:
#indexing technique

#1.basic indexing
import numpy as np
ar=np.array([10,20,30,40,50])
print("basic indexing:",ar[1])

#2.negative indexing
print("nagative indexing:",arr[-1])

#3.slicing indexing
print("slicing indexing:",ar[1:4])

#4.boolean indexing
arr=np.array([10,20,30,40,50])
print("boolean indexing:",arr[arr>25])

#5.fancy indexing
print("fancy indexing:",arr[[1,3]])

basic indexing: 20
nagative indexing: 50
slicing indexing: [20 30 40]
boolean indexing: [30 40 50]
fancy indexing: [20 40]


In [7]:
#joining horizontal and vertical and depth
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
#horizontal joining
result=np.hstack((arr1,arr2))
print("horizontal join:\n",result)
#vertical joining
result=np.vstack((arr1,arr2))
print("vertical join:\n",result)
#depth joining
result=np.dstack((arr1,arr2))
print("depth join:\n",result)

horizontal join:
 [[1 2 5 6]
 [3 4 7 8]]
vertical join:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
depth join:
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [11]:
#array splitting
import numpy as np
arr=np.array([1,2,3,4,5,6])
result=np.split(arr,3)
print("equal splitted:",result)
#unequal split
arr=np.array([1,2,3,4,5])
result=np.array_split(arr,3)
print("unequal array split:",result)

equal splitted: [array([1, 2]), array([3, 4]), array([5, 6])]
unequal array split: [array([1, 2]), array([3, 4]), array([5])]
