In [1]:
import numpy as np
a=np.array([1,2,3,4])
print("One dimension array:",a)

One dimension array: [1 2 3 4]


In [3]:
import numpy as np
b=np.array([[1,2,3,4],[4,5,6,7]])
print("Two dimension array:\n",b)

Two dimension array:
 [[1 2 3 4]
 [4 5 6 7]]


In [5]:
import numpy as np
c=np.array([[1,2,3,4],[5,6,7,8,],[9,10,11,12]])
print("Three dimension array:\n",c)

Three dimension array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
import numpy as np
d=np.zeros((4,4))
print("Array with all zeros:\n",d)

Array with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
import numpy as np
e=np.random.random((4,4))
print("Array with all zeros:\n",e)

Array with all zeros:
 [[0.00752398 0.87828269 0.98560526 0.13994401]
 [0.20143259 0.82876323 0.64718409 0.94756406]
 [0.61289593 0.01498698 0.65904014 0.4697168 ]
 [0.61167881 0.10601821 0.17148939 0.9228532 ]]


In [11]:
import numpy as np
f=np.arange(0,200,40)
print("Sequence array:",f)

Sequence array: [  0  40  80 120 160]


In [12]:
import numpy as np
org=np.array([[1,2,3,4],[5,6,7,8,],[9,10,11,12]])
new=org.reshape(4,3)
print("Original array:\n",org)
print("New array:\n",new)


Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
New array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
import numpy as np
org=np.array([[1,2,3,4],[5,6,7,8,],[9,10,11,12]])
fl=org.flatten()
print("Original array:\n",org)
print("Flattened array:",fl)

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [17]:

import numpy as np
ar=np.array([[[1,2,3,4],[5,6,7,8,],[9,10,11,12]],[[0,2,3,4],[6,3,5,1],[9,0,3,6]]])
print("Three dimension array:\n",ar)
print("The dimension of the aray:",ar.ndim)

Three dimension array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 0  2  3  4]
  [ 6  3  5  1]
  [ 9  0  3  6]]]
The dimension of the aray: 3


In [23]:
#array shape
print("Shape of the array:",ar.shape)

Shape of the array: (3, 4)


In [27]:
#array type
print("Type of the array:",ar.dtype)

Type of the array: int64


In [31]:
#size or lenght of array
size=len(ar[1])
print("size of the array:",size)

size of the array: 3


In [1]:
#change of datatype
import numpy as np
a=np.array([1,2,3])
newtype=a.astype('float64')
print(newtype)
print(newtype.dtype)

[1. 2. 3.]
float64
